name: Mac AnyDesk Remote

on:
  workflow_dispatch:

jobs:
  anydesk:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Install AnyDesk
        run: brew install --cask anydesk

      - name: Create Virtual Display
        run: |
          /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -
      - name: Keep Alive
        run: while true; do sleep 60; done
